apiVersion: v1
kind: Sevice
metadata:
  name: nginx1-service
spec:
    ports:
      - name: nginx1-service-port
        port: 80
        targetPort:80
    type: LoadBalancer
    selector:
        app:  nginx1-demo